### ISSUE TITLE
The `appropriate` way to initialize ReactGA on browser when using SSR

### ISSUE THREAD

**Issue by paulsoh** [react-ga/react-ga#182]
Thanks for the wonderful work!

I started using ReactGA when my app didn't use SSR and recently I moved some components(routes) to support SSR for SEO purposes.

I ran into the typical `window is not defined` errors along the way and I made fixes based on the snippets shared in the `Issues` section.

However, I noticed that ReactGA wasn't being initialized on the browser when using SSR.

I did some light research and to my understanding, it is because ReactGA.initialize isn't being called during the `SSR flow`.

1. User requests page from express

2. renderToString runs thru the component and skips the ReactGA.initialize part and sends rendered page and bundle.js to user.

3. The user gets the rendered page and bundle.js and navigates around where certain events should be logged via ReactGA but from the users browser perspective, ReactGA has never been initialzed.

Has anyone run into this issue? I'm curious how people made a fix around this problem.
Thanks!

**Comment by paulsoh** [comment]
I think I was too caught up with the idea that reactGA should be initialized at the server.

Resolved this issue by simply moving the initialize code into a componentDidMount lifecycle method within a HOC inside my app

**Comment by CharlesCarnell** [comment]
Hey @paulsoh,

Would you happen to still have an example of your react-ga HOC and be prepared to share it?

Kind regards
